### ISSUE TITLE
How to use the pre-train network

### ISSUE THREAD

**Issue by Leezus7** [Zuber-group/CryoVesNet#3]
I read the README.md file and i still don't know how to use the pre-train network?
by the way, what is *.rec.nad files? I only have mrc files.
Looking for your reply, thanks

**Comment by lgomez21** [comment]
I am having the same issue. If anyone has answers they would be greatly appreciated. Thanks.

**Comment by amineuron** [comment]
We apologize for the delay in responding. We've been busy with the paper rebuttal, but we're excited to share that a big refactor is coming soon. It'll make everything easier, including clear instructions for the pre-trained network and support for your .mrc files. Thanks for your patience and interest!

**Comment by amineuron** [comment]
Here's a temporary solution you can try, you can simply rename your file to .nad.rec, or use this imod command:
`nad_eed_3d  -k 1e10 -n 5  your_filename.mrc  your_filename.nad.rec`
This should help you get started. We'll have more comprehensive improvements coming soon!
